#mybatis
mybatis:
  type-aliases-package: com.army.ardiary.domain.entity #entity 경로(db 조회 결과인 resultType 패키지 사전 지정)
  mapper-locations: mapper/**/*.xml #매퍼.xml 경로

spring:
  application:
    name: ardiary
    profiles:
      active: dev
  jwt:
    secretKey: {Key}
  #mariadb
  datasource:
    #로그 출력
    url: jdbc:log4jdbc:mariadb://armydb.cy6dgaeyzjne.ap-northeast-2.rds.amazonaws.com:3306/ardiary_nf #접속DB명(rds쓸때는 localhost부분 엔드포인트로 바꿔주기), ardiary_nf: no foreign 외래키 속성 제거한 데이터베이스. 외래키 속성 사용하려면 _nf지우면 됨
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #로그 미출력
#    url: jdbc:mariadb://armydb.cy6dgaeyzjne.ap-northeast-2.rds.amazonaws.com:3306/ardiary_nf #접속DB명(rds쓸때는 localhost부분 엔드포인트로 바꿔주기), ardiary_nf: no foreign 외래키 속성 제거한 데이터베이스. 외래키 속성 사용하려면 _nf지우면 됨
#    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: 20220324
  #springfox 사용 가능
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8088
  forward-headers-strategy: framework

jwt:
  secretKey: armyJwtSecret12411128094456375876587
  #accessValidTime: 3600000 추후 별도 관리예정


cloud:
  aws:
    credentials:
      accessKey: AKIAYPNIJYGAWB47IOHU
      secretKey: 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
    s3:
      bucket: army-bucket0324
    region:
      static: ap-northeast-2
    stack:
      auto: false #프로젝트 배포시 default로 cloudFormatino구성을 시작하기 때문에 따로 설정되어있지 않으면 프로젝트가 실행되지 않으므로 해당 기능을 꺼놓음

logging:
  level:
    jdbc.sqlonly: DEBUG
    jdbc.sqltiming: off
    jdbc.resultsettable: info
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.connection: off