#mybatis
mybatis:
  type-aliases-package: com.army.ardiary.domain.entity #entity 경로(db 조회 결과인 resultType 패키지 사전 지정)
  mapper-locations: mapper/**/*.xml #매퍼.xml 경로

spring:
  application:
    name: ardiary
    profiles:
      active: dev
  jwt:
    secretKey: {Key}
#mariadb
  datasource:
    url: jdbc:mariadb://armydb.cy6dgaeyzjne.ap-northeast-2.rds.amazonaws.com:3306/ardiary_nf #접속DB명(rds쓸때는 localhost부분 엔드포인트로 바꿔주기), ardiary_nf: no foreign 외래키 속성 제거한 데이터베이스. 외래키 속성 사용하려면 _nf지우면 됨
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: 20220324

server:
  port: 8088
  forward-headers-strategy: framework

jwt:
  secretKey: armyJwtSecret
  #accessValidTime: 3600000 추후 별도 관리예정