name: Deploy to EC2
on:
  push:
    branches: [ "release" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Deploy main branch
    runs-on: ubuntu-latest

    steps:
      - name: Connect ssh and git pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PEM_KEY }}
          script: |
            cd army/ARdiray_Spring/ardiary/
            git checkout release
            git pull origin release
            kill `ps -ef | grep ardiary-0.0.1-SNAPSHOT.jar | grep -v grep | awk '{print $2}'`
            sudo ./gradlew build
            cd build/libs/
            nohup java -jar ardiary-0.0.1-SNAPSHOT.jar 2>&1 &
            
            
